### ISSUE TITLE
Terminal Does not work

### ISSUE THREAD

**Issue by godfoder** [bio-guoda/guoda-services#1]
When clicking on the New->Terminal option in the browser I get the following stack trace back (via the developer console):

API request failed (500): Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/notebook/base/handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/notebook/terminal/api_handlers.py", line 18, in post
    name, _ = self.terminal_manager.new_named_terminal()
  File "/usr/local/lib/python3.5/dist-packages/terminado/management.py", line 303, in new_named_terminal
    term = self.new_terminal()
  File "/usr/local/lib/python3.5/dist-packages/terminado/management.py", line 161, in new_terminal
    pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
  File "/usr/local/lib/python3.5/dist-packages/ptyprocess/ptyprocess.py", line 220, in spawn
    pid, fd = pty.fork()
  File "/usr/lib/python3.5/pty.py", line 96, in fork
    master_fd, slave_fd = openpty()
  File "/usr/lib/python3.5/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.5/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices

**Comment by godfoder** [comment]
Through many levels of debugging, this issue was being caused by the default ptmxmode on ubuntu xenial:

devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0

This results in a /dev/pts/ptmx file with a mode of 000. For some reason, inside of the spawned jupyterhub session, this file replaces /dev/ptmx, and ptys can no longer be opened. As a verification Manually chmoding /dev/pts/ptmx to 666 fixes the problem and the terminal launches. mount -o remount,ptmxmode=666 /dev/pts also seems to fix the problem.

The ubuntu start scripts that create this filesystem don't have a configurable option to modify this paramater, so we are adding an rc.local entry (ugh) to remount the filesystem on startup.

If anyone can figure out what is causing the /dev/ptmx replacement, i'm curious even though I have a fix.

**Comment by godfoder** [comment]
Confirmed fixed on reboot.
