### ISSUE TITLE
GUODA service down?

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#49]
I had several successful jobs a couple of days ago but today they're getting rejected. I don't think I'm trying during @diatomsRcool 's customary window, and I think @mjcollin 's adventures don't start until Thursday. Is anything wrong?

**Comment by mjcollin** [comment]
Yes, I think that was me. HDFS was unresponsive yesterday evening and I paused and redeployed the effecheka API but it looks like I did it wrong. HDFS and Mesos are up now, I think it's the effechecka API that's the issue. I'm nearly in Japan at a conference, it might be a day or so to get it running again.

**Comment by jhpoelen** [comment]
As far as I can tell, the last time the effechecka api changed was 22 Sept 2017. Also, at least one of the effechecka instances is starting ok. So, somewhere in the deployment of hdfs/mesos/effechecka something must have shifted. The only think I know is that the mesos master used not be mesos03. Hope this helps troubleshooting the issue.

**Comment by jhpoelen** [comment]
The api was up and running again after applying the original configuration (see https://github.com/bio-guoda/effechecka readme). For some reason, the old configuration got lost.

**Comment by jhpoelen** [comment]
However, after a couple of days, it appears that http://effechecka.org and https://gimmefreshdata.github.io are no longer receiving data.

Some observations:
1. All occurrence monitors are being updated and it's taking up all the resources.

2. For some reason, effechecka-api get kills within the hour, and is now resource deprived (because 1. is stealing resources that effechecka-api was using)

3. In processes part of 1. I am seeing all sorts of hdfs and spark errors (see below)

@mjcollin might have to look into why effechecka-api jobs are getting killed (perhaps the health check is not working as expected). Note that the health check relies on retrieving data from hdfs, which might be consistent with hdfs failures. Probably want to coordinate with @jhammock  and @diatomsRcool and halt effechecka / freshdata jobs so that you have room to troubleshoot.

from http://mesos03.acis.ufl.edu:5050/#/agents/dabbc59d-84c3-4fb3-8baa-045c55e020fb-S4/browse?path=%2Fvar%2Flib%2Fmesos%2Fslaves%2Fdabbc59d-84c3-4fb3-8baa-045c55e020fb-S4%2Fframeworks%2Fe97a8d30-e7b4-41aa-ab12-7dedb8eaa21e-0073-driver-20180523100936-112943%2Fexecutors%2F1%2Fruns%2Fa5e9717c-c047-462c-870c-2178709673c6 -
```
18/05/24 07:42:38 WARN FileOutputCommitter: Could not delete hdfs://hdfscluster/guoda/data/monitor/source-of-monitored-occurrence/_temporary/0/_temporary/attempt_20180524074236_0008_m_000813_0
18/05/24 07:42:38 ERROR FileFormatWriter: Job job_20180524074236_0008 aborted.
18/05/24 07:42:51 ERROR Utils: Aborting task
org.apache.spark.executor.CommitDeniedException: attempt_20180524074249_0008_m_000825_0: Not committed because the driver did not authorize commit
	at org.apache.spark.mapred.SparkHadoopMapRedUtil$.commitTask(SparkHadoopMapRedUtil.scala:83)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitTask(HadoopMapReduceCommitProtocol.scala:153)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:260)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:256)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1375)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:261)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:191)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:190)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/05/24 07:42:51 WARN FileOutputCommitter: Could not delete hdfs://hdfscluster/guoda/data/monitor/source-of-monitored-occurrence/_temporary/0/_temporary/attempt_20180524074249_0008_m_000825_0
18/05/24 07:42:51 ERROR FileFormatWriter: Job job_20180524074249_0008 aborted.
```
and a non-hdfs error from http://mesos03.acis.ufl.edu:5050/#/agents/673363d1-9ae0-4b31-80aa-09ff4994cc70-S0/browse?path=%2Fvar%2Flib%2Fmesos%2Fslaves%2F673363d1-9ae0-4b31-80aa-09ff4994cc70-S0%2Fframeworks%2Fe97a8d30-e7b4-41aa-ab12-7dedb8eaa21e-0073-driver-20180523100936-112943%2Fexecutors%2F14%2Fruns%2Fea7e1434-8e2f-406d-9786-e86a711886c9:

```
18/05/24 07:41:04 ERROR ShuffleBlockFetcherIterator: Failed to get block(s) from mesos02.acis.ufl.edu:36253
java.io.IOException: Connection from mesos02.acis.ufl.edu/10.13.44.18:36253 closed
	at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
	at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:227)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:220)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278)
```

**Comment by jhammock** [comment]
Thanks, @jhpoelen 
@mjcollin I did start a new update monitors job shortly before I noticed this. Shall I pause it? Or feel free to kill it if that's better. I think I'll need to go back a couple of updates and try again to increment from my March archives when the dust settles. I think that means this job doesn't matter.

**Comment by jhpoelen** [comment]
Some more sample from error logs of (up and running) effechecka-api - evidence suggests that the API is up, only cannot access hdfs .
```
18-05-26 18:38:23 WARN RetryInvocationHandler: Exception while invoking class org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo over mesos02.acis.ufl.edu/10.13.44.18:8020. Not retrying because failovers (15) exceeded maximum allowed (15)
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:87)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1774)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1313)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3856)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1006)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:843)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
```

and 
```
18-05-26 18:38:37 WARN RetryInvocationHandler: A failover has occurred since the start of this method invocation attempt.
[ERROR] Terminal initialization failed; falling back to unsupported
java.io.IOException: Cannot run program "sh": error=24, Too many open files
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:308)
	at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
	at jline.internal.TerminalLineSettings.set(TerminalLineSettings.java:148)
	at jline.UnixTerminal.init(UnixTerminal.java:92)
	at jline.TerminalFactory.create(TerminalFactory.java:122)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at sbt.MainLoop$$anon$1.run(MainLoop.scala:17)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=24, Too many open files
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
```

**Comment by mjcollin** [comment]
Using the gimme... interface as a test, the API can right now return an existing result set, ie load the main page with results. When I looked at the Marathon interface 15 minutes ago, 2 instances of the API where unhealthy and the tail of the error log for one of them was complaining about being out of file descriptors:

```
18-05-29 06:57:18 WARN BlockReaderFactory: I/O error constructing remote block reader.
java.net.SocketException: Too many open files
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.socket(Net.java:411)
	at sun.nio.ch.Net.socket(Net.java:404)
	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:105)
	at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:145)
	at org.apache.hadoop.net.StandardSocketFactory.createSocket(StandardSocketFactory.java:62)
	at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:3089)
	at org.apache.hadoop.hdfs.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:778)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:693)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:354)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:617)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:841)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:889)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:696)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.parquet.hadoop.util.H2SeekableInputStream.read(H2SeekableInputStream.java:59)
	at org.apache.parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:82)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:488)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:461)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:437)
	at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:259)
	at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18-05-29 06:57:18 WARN DFSClient: Failed to connect to /10.13.44.30:50010 for block, add to deadNodes and continue. java.net.SocketException: Too many open files
```

I came back to the Marathon interface a few minutes later and all 3 instances were healthy and from the logs it looks like they were all restarted.

Considering the one that I saw failing, it was started at 18-05-29 06:25:54 and started failing at 18-05-29 06:56:31 after a bunch (100-500) "looking for... " messages which I assume are successful requests.

My theory is that it's exhausting file descriptors and being restarted. Now, why is a different question.

**Comment by mjcollin** [comment]
And making a new gimme... query with a new geographic extent does kick off a Spark job that does return a new checklist (after ~32 minutes).

**Comment by jhammock** [comment]
I case this helps: 

My query du jour shows as ready in the widget

http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918%29%29

but the tsv has... a problem? It seems to exist, but fails to download. It's large, so maybe that's a problem on my machine, but it does look like it just about completes before it throws an error. Also, this is the query which would normally proceed to Eli's filtering process to remove "boring taxa of the greater DC area", on a nice robust SI server- and there also it is behaving like it didn't arrive.

http://api.effechecka.org/occurrences.tsv?wktString=POLYGON%20((-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918))

**Comment by mjcollin** [comment]
I think this is HDFS related. The open files limit is already set to ~1M so I looked at what files are open and CLOSE_WAIT connections to all the HDFS data nodes seem to accumulate.

A similar issue: https://issues.apache.org/jira/browse/HDFS-1836

**Comment by jhpoelen** [comment]
@mjcollin interesting . . . referenced issue seems to be from 2011. What do you think the root cause is?

**Comment by jhammock** [comment]
at my most recent test it seemed like some queries- even completely new ones- worked fine (eg: widget view: http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-77.30255126953125%2038.93377552819722%2C%20-77.30255126953125%2039.06611426153784%2C%20-77.05535888671874%2039.06611426153784%2C%20-77.05535888671874%2038.93377552819722%2C%20-77.30255126953125%2038.93377552819722%29%29)
while other (larger?) results sets may be truncated (eg: widget view, "download all as TSV" to see truncation, circa 2015: http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918%29%29)

**Comment by jhammock** [comment]
Interesting... today, the latter query, formerly truncated ~2015, behaves differently. 

http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918%29%29

When I try it from my laptop, it's "failed- network error". When I try the job from Eli's system (which harvests that query for filtering for DC potential invaders), the file is now truncated around August 2016.

**Comment by jhammock** [comment]
The behavior of the above query

(http://api.effechecka.org/occurrences.tsv?wktString=POLYGON%20((-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918))&monitorAPI=0)

seems to vary today. This morning, (10 or 11am) it attempted a download, got past 600MB, and failed with a network error. Two later attempts, one from the web widget, one from the Fresh Data admin tools, yielded the same truncated file as last time (stopping around August 2016). There are occasional  "not OK" errors. Just now, from the web widget, it got to 696MB and "failed- network error" again. 

Any ideas?

**Comment by jhammock** [comment]
weird. Today the truncated file is down to half the size, ending ~June 2015...

**Comment by mjcollin** [comment]
Effechecka stderr and stdout files are getting up to silly sizes - multiple GB. Need to fix this.

**Comment by jhpoelen** [comment]
thanks for looking into this. Reducing the log volume doable by adjusting the log levels on startup. Are the log file size the reason for the observed behavior by @jhammock ?

**Comment by jhammock** [comment]
I tried my favorite query again today, for comparison. The Fresh Data admin tool's truncated file is still truncated at June 2015. The widget download gets to 701MB before it failed. Looks like the situation is holding pretty steady, whatever it is.

**Comment by jhpoelen** [comment]
So, here's another potential root cause from late 2017: https://issues.apache.org/jira/browse/HDFS-6973

**Comment by jhpoelen** [comment]
Also see https://github.com/apache/parquet-mr/pull/388 .

**Comment by mjcollin** [comment]
I like this bug as a possible cause. In watching one of the nodes while it fails, stderr has a bunch of lines like this appearing at the rate of 1-2 per second starting immediately after startup:

```
18-07-12 16:17:11 INFO WebApi$: looking for [/guoda/data/monitor/checklist-summary/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53
df-8838-14d55bba8d4a]
18-07-12 16:17:12 INFO WebApi$: looking for [/guoda/data/monitor/checklist-summary/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53
df-8838-14d55bba8d4a]
18-07-12 16:17:13 INFO WebApi$: looking for [/guoda/data/monitor/checklist-summary/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53
df-8838-14d55bba8d4a]
18-07-12 16:17:13 INFO WebApi$: looking for [/guoda/data/monitor/checklist/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53df-8838-14d55bba8d4a]
...
18-07-12 16:46:20 INFO WebApi$: looking for [/guoda/data/monitor/checklist/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53df-8838-14d55bba8d4a]
18-07-12 16:46:23 INFO WebApi$: looking for [/guoda/data/monitor/checklist-summary/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53df-8838-14d55bba8d4a]
18-07-12 16:46:23 INFO WebApi$: looking for [/guoda/data/monitor/checklist-summary/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53df-8838-14d55bba8d4a]
```

After about 30 minutes of that, about 4000 "lookings", it dies with the "Too many open files" error. Also, the number of TCP connections in CLOSE_WAIT steadily goes up during this time to about 8000 (perhaps two connections per "looking") at which point the API instance goes unhealthy and the open files error occurs.

So, who/what is asking for checklists? Maybe this open connection issue has always existed and it just wasn't a major problem because it was days before enough checklists were requested to cause it to die so no one noticed it restarting. Now there's requests every second and the connections build up in 30 minutes.

Off to look for request logs to see why it's trying to load a bunch of various checklists continuously.

**Comment by mjcollin** [comment]
Oh, and too many open files can be the TCP connections and related state so upping the open file limit is unlikely to fix anything and it's not the way we had it set up before when it was working.

**Comment by jhpoelen** [comment]
@diatomsRcool is still running a water body checklist update every 5 minutes at http://archive.guoda.bio/view/Effechecka%20Jobs/job/water%20body%20checklist%20status%20checker/ .

**Comment by diatomsRcool** [comment]
Hmmm. That shouldn't be.

**Comment by diatomsRcool** [comment]
I think I just shut it off

**Comment by mjcollin** [comment]
Checking our HAproxy stats, since last counter reset the iDigBio api has had a total of 8M sessions and transferred 530 GB. Effechecka API has had a total of 43M sessions and transferred 25 GB. 
So good job with that code @jhpoelen , it's serving a lot of stuff.

**Comment by jhammock** [comment]
Gosh. Water bodies were completed awhile ago. @diatomsRcool you had the ecoregion queries still pending, I think, but weren't they paused a few weeks ago?

**Comment by mjcollin** [comment]
Requests are coming from Marathon itself directly to the effechecka API instances. The HDFS looking request is for the checklist that is returned when you load the URL that is the health check URL. So, of course, the health check is causing the thing to crash....

**Comment by diatomsRcool** [comment]
The only thing I can think is that its set to re-run when I update the 
GitHub and I've been updating documentation.

**Comment by mjcollin** [comment]
Actually, marathon was only holding open a connection, it is properly only issuing health checks every 60 seconds. What was issuing health checks every second was HAproxy and it was using a request for a checklist as it's check. I changed that to be a request for just "/ping". Now marathon will check every minute, which still tickles the bug in closing a connection but now they'll accumulate 60 times slower so it should stay up for 30 hours instead of minutes. Let's come back to that later and see if the API is more stable now.

**Comment by jhpoelen** [comment]
Thanks for poking around and making adjustments. The health check was meant to check  the entire stack, traversing through DHFS and back, not just to show that the api was reachable.

**Comment by mjcollin** [comment]
@jhammock Regarding your favorite query, when I try that I can watch the CLOSE_WAIT TCP connections increase on the API instance that is serving it up to about 8000 and I can get about 750 MB of data. Then the connection dies, the API instance is marked unhealthy, and it restarts. So, we definitely need to fix the connection issue.

**Comment by jhpoelen** [comment]
Thanks for reproducing . . . could you please revert the api health check to original settings?

**Comment by mjcollin** [comment]
@jhpoelen Yes, but haproxy is just too aggressive, even if the HDFS connections worked perfectly. I think Marathon doing the deep check every minute to make sure _some_ APIs are running and haproxy doing the shallow check every second to see _where_ the API is running is a good balance.

No, I don't know why this used to work better than it currently does :(

**Comment by jhpoelen** [comment]
I've done some surgery of effechecka to include a version of the parquet library (i.e. 1.8.3) that fixed the connection leak. I ran @jhammock favorite query and was able to download >1G of data without any crashes (see below). Please confirm.

```console
curl "http://api.effechecka.org/occurrences.tsv?wktString=POLYGON%20((-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918))&monitorAPI=0" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1126M    0 1126M    0     0  1008k      0 --:--:--  0:19:04 --:--:-- 17690
```

**Comment by jhammock** [comment]
Confirmed! Many thanks, @jhpoelen that was well beyond the call of duty.

**Comment by jhpoelen** [comment]
https://en.wikipedia.org/wiki/Pay_it_forward :+1:

**Comment by jhpoelen** [comment]
Thanks @mjcollin for sharing helpful observations.
