### ISSUE TITLE
jenkins at http://archive.guoda.bio appears out of disk space

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#50]
Seen at 2018-06-09 21:15:51,638 - 

Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at org.eol.globi.data.FileUtils.saveToTmpFile(FileUtils.java:26)
	at org.eol.globi.data.StudyImporterForSeltmann.importStudy(StudyImporterForSeltmann.java:77)
	... 7 more

**Comment by mjcollin** [comment]
Old builds, especially for jobs named *status checker* were not getting purged. I changed the job config to check the "delete old builds" checkbox. Rebooted host to make sure all services are clean after the disk being full.

**Comment by jhpoelen** [comment]
@mjcollin thanks!

@diatomsRcool from what I can tell, your checklist are all 200 (or done). If so, you might want to consider stopping the job for now.

**Comment by diatomsRcool** [comment]
I thought it was supposed to automatically stop?

**Comment by diatomsRcool** [comment]
I think I got it

**Comment by mjcollin** [comment]
Also, host is in monitoring and we will be alerted next time.
