### ISSUE TITLE
how to stop a jenkins job fails to stop

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#61]
For some reason, the updateMonitor job fails to be stopped forcibly. The job appears to have entered a state where jenkins thinks it is running, but nothing appears to be happening. 

I'll attempt applying suggestion in https://stackoverflow.com/questions/14456592/how-to-stop-an-unstoppable-zombie-job-on-jenkins-without-restarting-the-server#38481808 momentarily.

From http://archive.guoda.bio/job/update%20monitors/121/console -
```
Resuming build at Wed Nov 07 08:48:04 EST 2018 after Jenkins restart
Ready to run at Wed Nov 07 08:48:06 EST 2018
Aborted by Jorrit Poelen
Aborted by Jorrit Poelen
Click here to forcibly terminate running steps
Click here to forcibly terminate running steps
Aborted by Jorrit Poelen
Click here to forcibly terminate running steps
Aborted by Admin
Aborted by Jorrit Poelen
Click here to forcibly terminate running steps
Pausing
Click here to forcibly terminate running steps
Aborted by Admin
Click here to forcibly terminate running steps
Resuming build at Fri Nov 09 16:20:28 EST 2018 after Jenkins restart
Still paused
Aborted by Admin
Click here to forcibly terminate running steps
```

**Comment by jhpoelen** [comment]
After running:

```
Jenkins .instance.getItemByFullName("update monitors")
        .getBuildByNumber(121)
        .finish(hudson.model.Result.ABORTED, new java.io.IOException("Aborting build")); 
``` 
in the Jenkins > Manage Jenkins > Script Console , the job finally stopped. 

Note that "update monitors" is the name of the job, and "121" is the job number.

**Comment by jhpoelen** [comment]
@jhammock perhaps now is a good time restart the update monitors job, since @mjcollin has changed the hdfs configuration to help resolve #57  .

**Comment by jhammock** [comment]
I'll give it a try

**Comment by jhammock** [comment]
the job appeared to complete, but my [test query](http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918%29%29) still returns no results

**Comment by jhpoelen** [comment]
@jhammock sorry to hear that. I tried to do a postmortem (see screenshot), but, for some reason, the log files were no longer present. I have feeling that the constant checklist generation prompts the system to cleanup logs. On a good note, hdfs seem to have survived the updateMonitors run. Perhaps run again and let me know a little earlier? Let me know how you'd like to proceed. 

![screenshot from 2018-11-15 06-16-19](https://user-images.githubusercontent.com/1084872/48558437-24856980-e89e-11e8-8801-0991d2315bd6.png)
![screenshot from 2018-11-15 06-20-00](https://user-images.githubusercontent.com/1084872/48558595-83e37980-e89e-11e8-8e42-b119c4483470.png)

**Comment by jhammock** [comment]
I could do it now, or rather earlier tomorrow. This last run was wicked fast, possibly reflecting recent changes? 7.5 hours...

**Comment by jhpoelen** [comment]
perhaps the end of your day, so I can check in the morning?

**Comment by jhammock** [comment]
OK, I'll start it tonight.

**Comment by jhpoelen** [comment]
thanks - just checked and noticed (still running) -

ID | Name | State | Started | Host |  
-- | -- | -- | -- | -- | --
driver-20181115190744-5471305 | Driver for updateAll | RUNNING | 2018-11-15T16:07:53-0800 | mesos07.acis.ufl.edu | Sandbox

The updateAll job started around 7p eastern.

**Comment by jhpoelen** [comment]
Looks like the job completed - 
![screenshot from 2018-11-16 20-23-30](https://user-images.githubusercontent.com/1084872/48656844-797cc900-e9df-11e8-9eb6-cb72a358c728.png)

with the default query at http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29 

showing results - 
![screenshot from 2018-11-16 20-38-16](https://user-images.githubusercontent.com/1084872/48656878-a0d39600-e9df-11e8-9c5b-6a1583d413d7.png)

@jhammock Please double check.

**Comment by jhammock** [comment]
That's extra spooky. Jenkins thinks it's still running: http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/

![screen shot 2018-11-16 at 11 46 49 pm](https://user-images.githubusercontent.com/3026567/48656979-d5544b80-e9f9-11e8-8784-a72a4e31fcf5.png)

**Comment by jhpoelen** [comment]
Interesting. It looks like the work is done:

```
[Stage 6:====================================================>(2335 + 3) / 2338]
[Stage 6:====================================================>(2336 + 2) / 2338]
[Stage 6:====================================================>(2337 + 1) / 2338]
[Stage 6:=====================================================(2338 + 0) / 2338]
```

however, one of the workers said - 
```
18/11/15 19:08:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/11/16 20:08:03 WARN DFSClient: DFSOutputStream ResponseProcessor exception  for block BP-39156263-10.13.44.15-1472751803704:blk_1083425304_9684827
java.io.EOFException: Premature EOF: no length prefix available
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2282)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PipelineAck.readFields(PipelineAck.java:244)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer$ResponseProcessor.run(DFSOutputStream.java:733)
18/11/16 20:08:04 WARN DFSClient: Error Recovery for block BP-39156263-10.13.44.15-1472751803704:blk_1083425304_9684827 in pipeline DatanodeInfoWithStorage[10.13.44.42:50010,DS-186c27a1-551a-4858-b3b5-66d0ca77f100,DISK], DatanodeInfoWithStorage[10.13.44.18:50010,DS-fe737a0c-66a5-4d82-bb94-868f4955eb33,DISK], DatanodeInfoWithStorage[10.13.44.33:50010,DS-dad6339b-0810-487f-9761-55c9e43d6672,DISK]: bad datanode DatanodeInfoWithStorage[10.13.44.42:50010,DS-186c27a1-551a-4858-b3b5-66d0ca77f100,DISK]
18/11/16 20:08:07 WARN DFSClient: Slow waitForAckedSeqno took 30613ms (threshold=30000ms)
18/11/16 20:08:10 WARN DFSClient: Slow waitForAckedSeqno took 66552ms (threshold=30000ms)
18/11/16 22:08:17 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
18/11/16 22:08:27 WARN Executor: Issue communicating with driver in heartbeater
```

**Comment by jhpoelen** [comment]
and another worker, around the same time:
```
18/11/16 22:08:18 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
18/11/16 22:08:28 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
18/11/16 22:08:38 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
18/11/16 22:08:48 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
18/11/16 22:08:53 WARN TransportResponseHandler: Ignoring response for RPC 9041443748931019725 from /10.13.44.33:36628 (81 bytes) since it is not outstanding
18/11/16 22:08:53 WARN TransportResponseHandler: Ignoring response for RPC 5338562278522653138 from /10.13.44.33:36628 (81 bytes) since it is not outstanding
18/11/16 22:08:53 WARN TransportResponseHandler: Ignoring response for RPC 7034821207620269171 from /10.13.44.33:36628 (81 bytes) since it is not outstanding
18/11/16 22:08:53 WARN TransportResponseHandler: Ignoring response for RPC 5675715115264442537 from /10.13.44.33:36628 (81 bytes) since it is not outstanding
```

**Comment by jhpoelen** [comment]
Looks like it finished successfully. 

```
checking status {
  "action" : "SubmissionStatusResponse",
  "driverState" : "FINISHED",
  "message" : "task_id {\n  value: \"driver-20181115190744-5471305\"\n}\nstate: TASK_FINISHED\nmessage: \"Command exited with status 0\"\nslave_id {\n  value: \"e97a8d30-e7b4-41aa-ab12-7dedb8eaa21e-S1\"\n}\ntimestamp: 1.542449841239331E9\nexecutor_id {\n  value: \"driver-20181115190744-5471305\"\n}\nsource: SOURCE_EXECUTOR\nuuid: \"HpQ\\331i;G\\343\\223}<\\004\\0238\\276\\276\"\ncontainer_status {\n  network_infos {\n    ip_addresses {\n      ip_address: \"10.13.44.33\"\n    }\n  }\n  executor_pid: 32547\n}\n",
  "serverSparkVersion" : "2.2.0",
  "submissionId" : "driver-20181115190744-5471305",
  "success" : true
}
[Pipeline] }
[Pipeline] // waitUntil
[Pipeline] sh
[update monitors@2] Running shell script
+ curl --silent http://mesos07.acis.ufl.edu:7077/v1/submissions/status/driver-20181115190744-5471305
[Pipeline] echo
succeeded to update monitors
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by jhpoelen** [comment]
Jenkins was removed by @roncanepa due to security concerns. Closing issue.
