### ISSUE TITLE
hdfs not accessible - hdfs in standby mode 

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#71]
After a heavy load on hdfs due to unpacking of thousands of dwca, the hdfs node cluster appears to have switch to standby mode. 

To reproduce:
1. open a jupyter terminal
2. in the terminal, execute "hdfs dfs -ls /guoda/data/source=preston/data/"

expected result:
a list of directories in hdfs.

actual result:
"ls: Operation category READ is not supported in state standby"

after a verbose error logging that looks like:

```
2019-05-15 20:03:54,709 INFO  [main] retry.RetryInvocationHandler (RetryInvocationHandler.java:invoke(140))
- Exception while invoking getFileInfo of class ClientNamenodeProtocolTranslatorPB over mesos02.acis.ufl.edu
/10.13.44.18:8020 after 1 fail over attempts. Trying to fail over after sleeping for 542ms.
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is no
t supported in state standby
        at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:87)
        at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:17
74)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1313)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3856)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1006)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(Client
NamenodeProtocolServerSideTranslatorPB.java:843)
```

**Comment by jhpoelen** [comment]
fyi @ialzuru @mielliott @jhammock 

Note that I do not have the ability to fix this due to access restrictions, so am hoping to get some help on this.

**Comment by jhpoelen** [comment]
btw - I noticed this article on using Ceph as an alternative to hadoop -https://www.usenix.org/system/files/login/articles/73508-maltzahn.pdf . Perhaps it makes sense to simplify our deployment / maintenance by adopting Ceph, since iDigBio already administers a ceph instance.

**Comment by jhpoelen** [comment]
@ialzuru brought hdfs cluster back to life by restarting the hdfs name nodes (mesos01, mesos02) after noticing that their disks were full. Details on how to prevent this from happening not yet available.
