### ISSUE TITLE
jupyter.idigbio.org down

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#81]
I'd like to use https://jupyter.idigbio.org to access, and compute with, all GBIF / iDigBio occurrence data in a reliable and performant way. 

However, when I visited https://jupyter.idigbio.org, I got the following message: "503 Service Unavailable. No server is available to handle this request."

@mielliott @roncanepa I am aware there was some power event that occurred in Dec 2019 at ACIS. Is this outage related to that? When do you expect the service to be up and running again? Do you have any alternatives in mind?

**Comment by roncanepa** [comment]
Hello!  I found that that VM wasn't running--likely was never turned on after the shutdown. (I've noticed that some VMs don't have their "auto power on" setting.)

I've started it up and it looks like it's back up now.

**Comment by mielliott** [comment]
Thanks Ron! The Jupyter page is definitely back up, but it looks like HDFS is still down. Just trying to "ls" gave the following error:

```shell
mielliott@idb-jupyter1:~$ hdfs dfs -ls /                                                                                           
2020-02-04 10:43:30,567 INFO  [main] retry.RetryInvocationHandler (RetryInvocationHandler.java:invoke(140)) - Exception while invok
ing getFileInfo of class ClientNamenodeProtocolTranslatorPB over mesos02.acis.ufl.edu/10.13.44.18:8020 after 1 fail over attempts. 
Trying to fail over after sleeping for 1193ms.                                                                                     
java.net.NoRouteToHostException: No Route to Host from  idb-jupyter1.acis.ufl.edu/10.13.44.50 to mesos02.acis.ufl.edu:8020 failed on socket timeout exception: java.net.NoRouteToHostException: No route to host; For more details see:  http://wiki.apache.org/hadoop/NoRouteToHost                                                                                                                     
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                   
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                            
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                         
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)                                                       
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:758)                                                         
        at org.apache.hadoop.ipc.Client.call(Client.java:1480)                                                                     
        at org.apache.hadoop.ipc.Client.call(Client.java:1407)                                                                     
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)                                      
        at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)                                                                       
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamendeProtocolTranslatorPB.java:771)                                                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                             
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                           
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                   
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                        
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)                         
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)                               
        at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)                                                                      
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2116)                                                       
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)                                 
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)                                 
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)                                     
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301)                             
        at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:57)                                                             
        at org.apache.hadoop.fs.Globber.glob(Globber.java:265)                                                                     
        at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1655)                                                        
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:326)                                                     
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)                                                     
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)                                                    
        at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:201)                                                
        at org.apache.hadoop.fs.shell.Command.run(Command.java:165)                                                                
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)                                                                      
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)                                                               
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)                                                               
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)                                                                     
Caused by: java.net.NoRouteToHostException: No route to host                                                                       
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)                                                                
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)                                                  
        at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)                                         
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)                                                               
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495)                                                               
        at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:609)                                                
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:707)                                                 
        at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:370)                                                    
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)                                                            
        at org.apache.hadoop.ipc.Client.call(Client.java:1446)                                                                     
        ... 28 more                                                                                                                
2020-02-04 10:43:34,769 INFO  [main] retry.RetryInvocationHandler (RetryInvocationHandler.java:invoke(140)) - Exception while invoking getFileInfo of class ClientNamenodeProtocolTranslatorPB over mesos01.acis.ufl.edu/10.13.44.15:8020 after 2 fail over attempts. 
Trying to fail over after sleeping for 1280ms.
...
```

**Comment by roncanepa** [comment]
Ahh, yes.  The mesos nodes experienced some hardware failures when coming back up after the power outages.  That's still being worked on.

We can explore getting you a dump copy of some of the data if that would help you continue your work in the interim.

**Comment by jhpoelen** [comment]
@roncanepa thanks for the quick action. I was also able to open a terminal (see attached screenshot).
![Screenshot from 2020-02-04 08-37-11](https://user-images.githubusercontent.com/1084872/73765629-a5da4d80-4729-11ea-8f94-84293e12df2d.png)

@mielliott could you please open a separate issue for the hdfs outage (see also #77 ) ?
